/* 
 * CDR API
 *
 * Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.CDR.Client;
using Cloudmersive.APIClient.NETCore.CDR.Model;

namespace Cloudmersive.APIClient.NETCore.CDR.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFileSanitizationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Content Disarm and Reconstruction on a File
        /// </summary>
        /// <remarks>
        /// Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>byte[]</returns>
        byte[] CallFile (System.IO.Stream inputFile = null);

        /// <summary>
        /// Content Disarm and Reconstruction on a File
        /// </summary>
        /// <remarks>
        /// Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> CallFileWithHttpInfo (System.IO.Stream inputFile = null);
        /// <summary>
        /// Content Disarm and Reconstruction on a File with PDFA Output
        /// </summary>
        /// <remarks>
        /// Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>byte[]</returns>
        byte[] FileToPdf (System.IO.Stream inputFile = null);

        /// <summary>
        /// Content Disarm and Reconstruction on a File with PDFA Output
        /// </summary>
        /// <remarks>
        /// Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> FileToPdfWithHttpInfo (System.IO.Stream inputFile = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Content Disarm and Reconstruction on a File
        /// </summary>
        /// <remarks>
        /// Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> CallFileAsync (System.IO.Stream inputFile = null);

        /// <summary>
        /// Content Disarm and Reconstruction on a File
        /// </summary>
        /// <remarks>
        /// Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> CallFileAsyncWithHttpInfo (System.IO.Stream inputFile = null);
        /// <summary>
        /// Content Disarm and Reconstruction on a File with PDFA Output
        /// </summary>
        /// <remarks>
        /// Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> FileToPdfAsync (System.IO.Stream inputFile = null);

        /// <summary>
        /// Content Disarm and Reconstruction on a File with PDFA Output
        /// </summary>
        /// <remarks>
        /// Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> FileToPdfAsyncWithHttpInfo (System.IO.Stream inputFile = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FileSanitizationApi : IFileSanitizationApi
    {
        private Cloudmersive.APIClient.NETCore.CDR.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FileSanitizationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FileSanitizationApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.CDR.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.CDR.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileSanitizationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FileSanitizationApi(Cloudmersive.APIClient.NETCore.CDR.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.CDR.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.CDR.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.CDR.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.CDR.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Content Disarm and Reconstruction on a File Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>byte[]</returns>
        public byte[] CallFile (System.IO.Stream inputFile = null)
        {
             ApiResponse<byte[]> localVarResponse = CallFileWithHttpInfo(inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Content Disarm and Reconstruction on a File Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > CallFileWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./cdr/sanitization/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CallFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Content Disarm and Reconstruction on a File Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> CallFileAsync (System.IO.Stream inputFile = null)
        {
             ApiResponse<byte[]> localVarResponse = await CallFileAsyncWithHttpInfo(inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Content Disarm and Reconstruction on a File Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> CallFileAsyncWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./cdr/sanitization/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CallFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Content Disarm and Reconstruction on a File with PDFA Output Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>byte[]</returns>
        public byte[] FileToPdf (System.IO.Stream inputFile = null)
        {
             ApiResponse<byte[]> localVarResponse = FileToPdfWithHttpInfo(inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Content Disarm and Reconstruction on a File with PDFA Output Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > FileToPdfWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./cdr/sanitization/file/to/pdf";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FileToPdf", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Content Disarm and Reconstruction on a File with PDFA Output Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> FileToPdfAsync (System.IO.Stream inputFile = null)
        {
             ApiResponse<byte[]> localVarResponse = await FileToPdfAsyncWithHttpInfo(inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Content Disarm and Reconstruction on a File with PDFA Output Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.CDR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to extract data from (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> FileToPdfAsyncWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./cdr/sanitization/file/to/pdf";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FileToPdf", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

    }
}
